[16.0][ADD] lighting_reporting_product
nuobit/lighting-vertical pull request #50
Opened 2024-06-20 15:42 UTC by FrankC013

2024-07-01 19:20 UTC, eantones requested changes

2024-07-01 19:20 UTC, eantones commented on lighting_reporting_product/controllers/main.py
> +            "/web/datasheet/<string:company_id>/<string:param1>/<string:param2>"
```suggestion
            "/web/datasheet/<int:company_id>/<string:param1>/<string:param2>"
```

2024-07-01 19:20 UTC, eantones commented on lighting_reporting_vanguard_product/report/report_vanguard.py
> +        company = self.env.company
This and all the other changes should be done on Classic as well. During test phase we're gonna need Classic to work in production and it cannot fail at all. No only Vanguard but Classic should also be tested intensively.

2024-07-03 14:16 UTC, FrankC013 commented
@eantones Pending to merge #53 and rebase

2024-07-03 17:01 UTC, eantones requested changes

2024-07-03 17:01 UTC, eantones commented on lighting_reporting_vanguard_product/views/report_vanguard.xml
>                                      t-att-src="image_data_uri(doc.catalog_ids[0].image_512)"
Put "doc.catalog_ids[0].image_512" in a t-value/t-set

2024-07-03 17:01 UTC, eantones commented on lighting_reporting_vanguard_product/views/report_vanguard.xml
> +                                                    t-if="line.get_dependent_field_value('color_temperature_flux_ids')"
Remember, it's not the same
```suggestion
                                                    t-if="line.get_dependent_field_value('color_temperature_flux_ids')" is not None"
```
do the same on the other ones

2024-07-04 07:46 UTC, eantones approved these changes

2024-07-04 14:06 UTC, FrankC013 commented
Pending to merge #53 and rebase

2024-07-04 15:50 UTC, eantones requested changes
Please squash

2024-07-05 09:25 UTC, FrankC013 commented
@eantones I had to use a combined approach with Python because if I only use the template tools, the decimal separator is not respected

2024-07-05 09:31 UTC, eantones requested changes

2024-07-05 09:31 UTC, eantones commented on lighting/models/product_source_line.py
> +            rec.total_flux_display = ", ".join(flux_values)
These codes are identical.

2024-07-05 12:45 UTC, eantones approved these changes

2024-07-05 14:29 UTC, eantones requested changes

2024-07-05 14:29 UTC, eantones commented on lighting/models/product_source_line.py
> +        )
```suggestion
def _get_color_temperature_flux_values(self, flux_attr):
    self.ensure_one()
    found = False
    flux_data = []
    for flux in self.color_temperature_flux_ids:
        value = flux[flux_attr]
        if value:
            value += flux.flux_magnitude
            if not found:
                found = True
        else:
            value = "-"
        flux_data.append(value)
    if found:
        return "/".join(flux_data)
    return found
```

2024-07-08 08:20 UTC, eantones requested changes

2024-07-08 08:20 UTC, eantones commented on lighting/models/product_source_line.py
> +        return found
```suggestion
        return found and "/".join(flux_data)
```

2024-07-08 08:28 UTC, eantones approved these changes

2024-07-09 12:58 UTC, merged