[16.0][FIX] lighting: field invisibility based on parameters in lighting source lines
nuobit/lighting-vertical pull request #53
Opened 2024-07-01 14:35 UTC by FrankC013

2024-07-01 19:22 UTC, eantones requested changes
Please, make the changes we discussed in today's meeting

2024-07-01 19:25 UTC, eantones requested changes

2024-07-01 19:25 UTC, eantones commented on lighting/models/product_source_line.py
> +            ]
Put this outside "for rec in self", maybe outside the class as a constant? What do you think?

2024-07-03 16:14 UTC, eantones requested changes

2024-07-03 16:14 UTC, eantones commented on lighting/models/product_source_line.py
> +    @api.model
Maybe using property will be similar to a constant.
```suggestion
    @property
```
chack for examples in Odoo

2024-07-03 16:14 UTC, eantones commented on lighting/models/product_source_line.py
> +    @api.model
Same

2024-07-03 16:14 UTC, eantones commented on lighting/models/product_source_line.py
> +    def GROUP_MAP(self):
Same

2024-07-03 16:14 UTC, eantones commented on lighting/models/product_source_line.py
> +                values[field] = None
We should have all these methods at the beginning just after the "constants" and comment the start and end of the block

2024-07-03 16:14 UTC, eantones commented on lighting/models/product_source_line.py
> +    def _get_all_dependent_fields(self):
To be like the others?
```suggestion
    def _get_dependent_all_fields(self):
```

2024-07-03 16:14 UTC, eantones commented on lighting/models/product_source_line.py
> +    def _get_irrelevant_dependent_fields(self, values=None):
To be like the others?
```suggestion
    def  _get_dependant_irrelevant_fields(self, values=None):
```

2024-07-03 16:14 UTC, eantones commented on lighting/models/product_source_line.py
> +    def _get_relevant_dependent_fields(self, values=None):
To be like the others?
```suggestion
    def  _get_dependant_relevant_fields(self, values=None):
```

2024-07-03 16:14 UTC, eantones commented on lighting/models/product_source_line.py
> +        # definition of VISIBLE fields (easier that the invisible)
Remove this

2024-07-04 07:47 UTC, eantones approved these changes

2024-07-04 07:48 UTC, eantones requested changes
CI is red

2024-07-04 09:00 UTC, eantones approved these changes

2024-07-04 09:57 UTC, FrankC013 commented
@eantones Continue WIP. One moment

2024-07-04 10:07 UTC, eantones commented
I won't do anything til the combination of labels were the correct ones. If it's wor in progress i'll do nothing.

2024-07-04 13:28 UTC, eantones requested changes

2024-07-04 13:28 UTC, eantones commented on lighting/views/views.xml
> +                                />
What would happen if a source has 3 lines and one line has 'lamp included' filled in but it is not a relevant field, and another line has 'lamp included' filled in and it is relevant? The column would then be displayed, and the column would show the 'is_lamp_included' activated for the line where it is not relevant, right?

2024-07-04 15:40 UTC, eantones approved these changes

2024-07-04 15:40 UTC, merged